version: "3.7"
services:
  app:
    build:
      args:
        user: todo
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: todo
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todo

  db:
    image: mysql:5.7
    container_name: todo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log/mysql
    networks:
      - todo

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - todo

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/log/nginx:/var/log/nginx
    networks:
      - todo

networks:
  todo:
    driver: bridge